title: Starter
image: logo.png
description: Start your own demo
priority: 99
jsfiddle:
  mapping:
    html: "index.html"
    css: "plp.css"
    js: "plp.js"
  resources:
    - "{{{fsi.server}}}/{{{fsi.context}}}/{{{fsi.viewer}}}/applications/touchzoom/js/fsitouchzoom.js"
